"""add_profile_image_to_users

Revision ID: 3d71d27c7a91
Revises: 
Create Date: 2026-05-29 15:19:59.614268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d71d27c7a91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_study_summary_study_date'), table_name='daily_study_summary')
    op.drop_index(op.f('ix_daily_study_summary_summary_id'), table_name='daily_study_summary')
    op.drop_index(op.f('ix_daily_study_summary_user_id'), table_name='daily_study_summary')
    op.drop_table('daily_study_summary')
    op.drop_index(op.f('ix_conversation_turn_turn_id'), table_name='conversation_turn')
    op.drop_table('conversation_turn')
    op.add_column('users', sa.Column('profile_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    op.create_table('conversation_turn',
    sa.Column('turn_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('turn_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_input', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_pass', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('feedback_ko', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('corrected_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_session.session_id'], name=op.f('conversation_turn_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('turn_id', name=op.f('conversation_turn_pkey'))
    )
    op.create_index(op.f('ix_conversation_turn_turn_id'), 'conversation_turn', ['turn_id'], unique=False)
    op.create_table('daily_study_summary',
    sa.Column('summary_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('study_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_energy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('summary_id', name=op.f('daily_study_summary_pkey')),
    sa.UniqueConstraint('user_id', 'study_date', 'type', name=op.f('_user_date_type_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_daily_study_summary_user_id'), 'daily_study_summary', ['user_id'], unique=False)
    op.create_index(op.f('ix_daily_study_summary_summary_id'), 'daily_study_summary', ['summary_id'], unique=False)
    op.create_index(op.f('ix_daily_study_summary_study_date'), 'daily_study_summary', ['study_date'], unique=False)
    # ### end Alembic commands ###
